version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
    volumes:
      - qdrant_data:/qdrant/storage

  ui:
    build: ./ui
    ports:
      - '3000:3000'
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - app

volumes:
  qdrant_data: 